/** @type {import('next').NextConfig} */
const nextConfig = {
  poweredByHeader: false,
  async redirects() {
    return [
      { source: '/UserBackend', destination: '/account', permanent: true },
      { source: '/UserBackend/profile', destination: '/account/profile', permanent: true },
      { source: '/UserBackend/addresses', destination: '/account/addresses', permanent: true },
      { source: '/UserBackend/orders', destination: '/account/orders', permanent: true },
      { source: '/UserBackend/orders/:orderId', destination: '/account/orders/:orderId', permanent: true },
      { source: '/UserBackend/messages', destination: '/account/messages', permanent: true },
      { source: '/UserBackend/notifications', destination: '/account/notifications', permanent: true },
      { source: '/UserBackend/wishlist', destination: '/account/wishlist', permanent: true },
      { source: '/UserBackend/browsing-history', destination: '/account/history', permanent: true },
      { source: '/UserBackend/reviews', destination: '/account/reviews', permanent: true },
      { source: '/UserBackend/followed-stores', destination: '/account/following', permanent: true },
      { source: '/UserBackend/account-security', destination: '/account/security', permanent: true },
      { source: '/UserBackend/shop-access', destination: '/account/shop-access', permanent: true },
      { source: '/backend/admin', destination: '/admin/dashboard', permanent: true },
      { source: '/backend/admin/dashboard', destination: '/admin/dashboard', permanent: true },
      { source: '/backend/admin/orders', destination: '/admin/orders', permanent: true },
      { source: '/backend/admin/messages', destination: '/admin/messages', permanent: true },
      { source: '/backend/admin/products', destination: '/admin/products', permanent: true },
      { source: '/backend/admin/notifications', destination: '/admin/notifications', permanent: true },
      { source: '/backend/admin/reviews', destination: '/admin/reviews', permanent: true },
      { source: '/backend/admin/customers', destination: '/admin/customers', permanent: true },
      { source: '/backend/admin/categories', destination: '/admin/categories', permanent: true },
      { source: '/backend/admin/brands', destination: '/admin/brands', permanent: true },
      { source: '/backend/admin/tags', destination: '/admin/tags', permanent: true },
      { source: '/backend/admin/attributes', destination: '/admin/attributes', permanent: true },
      { source: '/backend/admin/library', destination: '/admin/library', permanent: true },
      { source: '/backend/admin/size-guides', destination: '/admin/size-guides', permanent: true },
      { source: '/backend/admin/logistics', destination: '/admin/logistics', permanent: true },
      { source: '/backend/admin/pages', destination: '/admin/pages', permanent: true },
      { source: '/backend/admin/pages/home', destination: '/admin/pages/home', permanent: true },
      { source: '/backend/admin/settings', destination: '/admin/settings', permanent: true },
      { source: '/backend/admin/extra', destination: '/admin/extra', permanent: true },
      { source: '/backend/admin/shortcut', destination: '/admin/shortcut', permanent: true },
      { source: '/backend/admin/templates', destination: '/admin/templates', permanent: true },
      { source: '/vendors/:slug', destination: '/:slug', permanent: true },
      { source: '/store/:slug', destination: '/:slug', permanent: true },
      { source: '/help-center', destination: '/help', permanent: true },
      { source: '/help-center/:sectionId/:articleId', destination: '/help/:sectionId/:articleId', permanent: true },
    ]
  },
  async rewrites() {
    return [
      { source: '/account', destination: '/UserBackend' },
      { source: '/account/profile', destination: '/UserBackend/profile' },
      { source: '/account/addresses', destination: '/UserBackend/addresses' },
      { source: '/account/orders', destination: '/UserBackend/orders' },
      { source: '/account/orders/:orderId', destination: '/UserBackend/orders/:orderId' },
      { source: '/account/messages', destination: '/UserBackend/messages' },
      { source: '/account/notifications', destination: '/UserBackend/notifications' },
      { source: '/account/wishlist', destination: '/UserBackend/wishlist' },
      { source: '/account/history', destination: '/UserBackend/browsing-history' },
      { source: '/account/reviews', destination: '/UserBackend/reviews' },
      { source: '/account/following', destination: '/UserBackend/followed-stores' },
      { source: '/account/security', destination: '/UserBackend/account-security' },
      { source: '/account/shop-access', destination: '/UserBackend/shop-access' },
      { source: '/admin/dashboard', destination: '/backend/admin/dashboard' },
      { source: '/admin/orders', destination: '/backend/admin/orders' },
      { source: '/admin/messages', destination: '/backend/admin/messages' },
      { source: '/admin/products', destination: '/backend/admin/products' },
      { source: '/admin/notifications', destination: '/backend/admin/notifications' },
      { source: '/admin/reviews', destination: '/backend/admin/reviews' },
      { source: '/admin/customers', destination: '/backend/admin/customers' },
      { source: '/admin/categories', destination: '/backend/admin/categories' },
      { source: '/admin/brands', destination: '/backend/admin/brands' },
      { source: '/admin/tags', destination: '/backend/admin/tags' },
      { source: '/admin/attributes', destination: '/backend/admin/attributes' },
      { source: '/admin/library', destination: '/backend/admin/library' },
      { source: '/admin/size-guides', destination: '/backend/admin/size-guides' },
      { source: '/admin/logistics', destination: '/backend/admin/logistics' },
      { source: '/admin/pages', destination: '/backend/admin/pages' },
      { source: '/admin/pages/home', destination: '/backend/admin/pages/home' },
      { source: '/admin/settings', destination: '/backend/admin/settings' },
      { source: '/admin/extra', destination: '/backend/admin/extra' },
      { source: '/admin/shortcut', destination: '/backend/admin/shortcut' },
      { source: '/admin/store-front', destination: '/backend/admin/store-front' },
      { source: '/admin/templates', destination: '/backend/admin/templates' },
      { source: '/help', destination: '/help-center' },
      { source: '/help/:sectionId/:articleId', destination: '/help-center/:sectionId/:articleId' },
    ]
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
        ],
      },
    ]
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'pub-b2870c497b454b119731b14f509756fa.r2.dev',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'media.alxora.com',
        pathname: '/**',
      },
    ],
  },
}

module.exports = nextConfig
