const INTERNATIONAL_COUNTRY = 'International'

const DEFAULT_COUNTRY = 'Nigeria'

const NIGERIAN_STATES = [
  'Abia',
  'Abuja',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
]

const NIGERIAN_CITIES_BY_STATE = {
  abia: [
    'Abia - Aba North',
    'Abia - Aba South',
    'Abia - Arochukwu',
    'Abia - Bende',
    'Abia - Ikwuano',
    'Abia - Isiala-Ngwa North',
    'Abia - Isiala-Ngwa South',
    'Abia - Isuikwato',
    'Abia - Obi Ngwa',
    'Abia - Ohafia',
    'Abia - Osisioma Ngwa',
    'Abia - Ugwunagbo',
    'Abia - Ukwa East',
    'Abia - Ukwa West',
    'Abia - Umu-Nneochi',
    'Abia - Umuahia North',
    'Abia - Umuahia South',
  ],
  abuja: [
    'Abuja - Abaji',
    'Abuja - Abuja Municipal Area',
    'Abuja - Bwari',
    'Abuja - Gwagwalada',
    'Abuja - Kuje',
    'Abuja - Kwali',
  ],
  adamawa: [
    'Adamawa - Demsa',
    'Adamawa - Fufore',
    'Adamawa - Ganye',
    'Adamawa - Girie',
    'Adamawa - Gombi',
    'Adamawa - Guyuk',
    'Adamawa - Hong',
    'Adamawa - Jada',
    'Adamawa - Lamurde',
    'Adamawa - Madagali',
    'Adamawa - Maiha',
    'Adamawa - Mayo-Belwa',
    'Adamawa - Michika',
    'Adamawa - Mubi North',
    'Adamawa - Mubi South',
    'Adamawa - Numan',
    'Adamawa - Shelleng',
    'Adamawa - Song',
    'Adamawa - Toungo',
    'Adamawa - Yola North',
    'Adamawa - Yola South',
  ],
  'akwa ibom': [
    'Akwa Ibom - Abak',
    'Akwa Ibom - Eastern Obolo',
    'Akwa Ibom - Eket',
    'Akwa Ibom - Esit Eket',
    'Akwa Ibom - Essien Udim',
    'Akwa Ibom - Etim Ekpo',
    'Akwa Ibom - Etinan',
    'Akwa Ibom - Ibeno',
    'Akwa Ibom - Ibesikpo Asutan',
    'Akwa Ibom - Ibiono Ibom',
    'Akwa Ibom - Ika',
    'Akwa Ibom - Ikono',
    'Akwa Ibom - Ikot Abasi',
    'Akwa Ibom - Ikot Ekpene',
    'Akwa Ibom - Ini',
    'Akwa Ibom - Itu',
    'Akwa Ibom - Mbo',
    'Akwa Ibom - Mkpat Enin',
    'Akwa Ibom - Nsit Atai',
    'Akwa Ibom - Nsit Ibom',
    'Akwa Ibom - Nsit Ubium',
    'Akwa Ibom - Obot Akara',
    'Akwa Ibom - Okobo',
    'Akwa Ibom - Onna',
    'Akwa Ibom - Oron',
    'Akwa Ibom - Oruk Anam',
    'Akwa Ibom - Udung Uko',
    'Akwa Ibom - Ukanafun',
    'Akwa Ibom - Uruan',
    'Akwa Ibom - Urue-Offong/Oruko',
    'Akwa Ibom - Uyo',
  ],
  anambra: [
    'Anambra - Aguata',
    'Anambra - Anambra East',
    'Anambra - Anambra West',
    'Anambra - Anaocha',
    'Anambra - Awka North',
    'Anambra - Awka South',
    'Anambra - Ayamelum',
    'Anambra - Dunukofia',
    'Anambra - Ekwusigo',
    'Anambra - Idemili North',
    'Anambra - Idemili South',
    'Anambra - Ihiala',
    'Anambra - Njikoka',
    'Anambra - Nnewi North',
    'Anambra - Nnewi South',
    'Anambra - Ogbaru',
    'Anambra - Onitsha North',
    'Anambra - Onitsha South',
    'Anambra - Orumba North',
    'Anambra - Orumba South',
    'Anambra - Oyi',
  ],
  bauchi: [
    'Bauchi - Alkaleri',
    'Bauchi - Bauchi',
    'Bauchi - Bogoro',
    'Bauchi - Damban',
    'Bauchi - Darazo',
    'Bauchi - Dass',
    'Bauchi - Gamawa',
    'Bauchi - Ganjuwa',
    'Bauchi - Giade',
    'Bauchi - Itas/Gadau',
    'Bauchi - Jama’are',
    'Bauchi - Katagum',
    'Bauchi - Kirfi',
    'Bauchi - Misau',
    'Bauchi - Ningi',
    'Bauchi - Shira',
    'Bauchi - Tafawa-Balewa',
    'Bauchi - Toro',
    'Bauchi - Warji',
    'Bauchi - Zaki',
  ],
  bayelsa: [
    'Bayelsa - Brass',
    'Bayelsa - Ekeremor',
    'Bayelsa - Kolokuma/Opokuma',
    'Bayelsa - Nembe',
    'Bayelsa - Ogbia',
    'Bayelsa - Sagbama',
    'Bayelsa - Southern Ijaw',
    'Bayelsa - Yenegoa',
  ],
  benue: [
    'Benue - Ado',
    'Benue - Agatu',
    'Benue - Apa',
    'Benue - Buruku',
    'Benue - Gboko',
    'Benue - Guma',
    'Benue - Gwer East',
    'Benue - Gwer West',
    'Benue - Katsina-Ala',
    'Benue - Konshisha',
    'Benue - Kwande',
    'Benue - Logo',
    'Benue - Makurdi',
    'Benue - Obi',
    'Benue - Ogbadibo',
    'Benue - Ohimini',
    'Benue - Oju',
    'Benue - Okpokwu',
    'Benue - Oturkpo',
    'Benue - Tarka',
    'Benue - Ukum',
    'Benue - Ushongo',
    'Benue - Vandeikya',
  ],
  borno: [
    'Borno - Abadam',
    'Borno - Askira/Uba',
    'Borno - Bama',
    'Borno - Bayo',
    'Borno - Biu',
    'Borno - Chibok',
    'Borno - Damboa',
    'Borno - Dikwa',
    'Borno - Gubio',
    'Borno - Guzamala',
    'Borno - Gwoza',
    'Borno - Hawul',
    'Borno - Jere',
    'Borno - Kaga',
    'Borno - Kala/Balge',
    'Borno - Konduga',
    'Borno - Kukawa',
    'Borno - Kwaya Kusar',
    'Borno - Mafa',
    'Borno - Magumeri',
    'Borno - Maiduguri',
    'Borno - Marte',
    'Borno - Mobbar',
    'Borno - Monguno',
    'Borno - Ngala',
    'Borno - Nganzai',
    'Borno - Shani',
  ],
  'cross river': [
    'Cross River - Abi',
    'Cross River - Akamkpa',
    'Cross River - Akpabuyo',
    'Cross River - Bakassi',
    'Cross River - Bekwarra',
    'Cross River - Biase',
    'Cross River - Boki',
    'Cross River - Calabar South',
    'Cross River - Calabar-Municipal',
    'Cross River - Etung',
    'Cross River - Ikom',
    'Cross River - Obanliku',
    'Cross River - Obubra',
    'Cross River - Obudu',
    'Cross River - Odukpani',
    'Cross River - Ogoja',
    'Cross River - Yakurr',
    'Cross River - Yala',
  ],
  delta: [
    'Delta - Aniocha North',
    'Delta - Aniocha South',
    'Delta - Bomadi',
    'Delta - Burutu',
    'Delta - Ethiope East',
    'Delta - Ethiope West',
    'Delta - Ika North East',
    'Delta - Ika South',
    'Delta - Isoko North',
    'Delta - Isoko South',
    'Delta - Ndokwa East',
    'Delta - Ndokwa West',
    'Delta - Okpe',
    'Delta - Oshimili North',
    'Delta - Oshimili South',
    'Delta - Patani',
    'Delta - Sapele',
    'Delta - Udu',
    'Delta - Ughelli North',
    'Delta - Ughelli South',
    'Delta - Ukwuani',
    'Delta - Uvwie',
    'Delta - Warri North',
    'Delta - Warri South',
    'Delta - Warri South West',
  ],
  ebonyi: [
    'Ebonyi - Abakaliki',
    'Ebonyi - Afikpo North',
    'Ebonyi - Afikpo South',
    'Ebonyi - Ebonyi',
    'Ebonyi - Ezza North',
    'Ebonyi - Ezza South',
    'Ebonyi - Ikwo',
    'Ebonyi - Ishielu',
    'Ebonyi - Ivo',
    'Ebonyi - Izzi',
    'Ebonyi - Ohaozara',
    'Ebonyi - Ohaukwu',
    'Ebonyi - Onicha',
  ],
  edo: [
    'Edo - Akoko-Edo',
    'Edo - Egor',
    'Edo - Esan Central',
    'Edo - Esan North East',
    'Edo - Esan South East',
    'Edo - Esan West',
    'Edo - Etsako Central',
    'Edo - Etsako East',
    'Edo - Etsako West',
    'Edo - Igueben',
    'Edo - Ikpoba-Okha',
    'Edo - Oredo',
    'Edo - Orhionmwon',
    'Edo - Ovia North East',
    'Edo - Ovia South West',
    'Edo - Owan East',
    'Edo - Owan West',
    'Edo - Uhunmwonde',
  ],
  ekiti: [
    'Ekiti - Ado Ekiti',
    'Ekiti - Aiyekire',
    'Ekiti - Efon',
    'Ekiti - Ekiti East',
    'Ekiti - Ekiti South West',
    'Ekiti - Ekiti West',
    'Ekiti - Emure',
    'Ekiti - Idosi-Osi',
    'Ekiti - Ijero',
    'Ekiti - Ikere',
    'Ekiti - Ikole',
    'Ekiti - Ilejemeje',
    'Ekiti - Irepodun/Ifelodun',
    'Ekiti - Ise/Orun',
    'Ekiti - Moba',
    'Ekiti - Oye',
  ],
  enugu: [
    'Enugu - Aninri',
    'Enugu - Awgu',
    'Enugu - Enugu East',
    'Enugu - Enugu North',
    'Enugu - Enugu South',
    'Enugu - Ezeagu',
    'Enugu - Igbo-Etiti',
    'Enugu - Igbo-Eze North',
    'Enugu - Igbo-Eze South',
    'Enugu - Isi-Uzo',
    'Enugu - Nkanu East',
    'Enugu - Nkanu West',
    'Enugu - Nsukka',
    'Enugu - Oji-River',
    'Enugu - Udenu',
    'Enugu - Udi',
    'Enugu - Uzo-Uwani',
  ],
  gombe: [
    'Gombe - Akko',
    'Gombe - Balanga',
    'Gombe - Billiri',
    'Gombe - Dukku',
    'Gombe - Funakaye',
    'Gombe - Gombe',
    'Gombe - Kaltungo',
    'Gombe - Kwami',
    'Gombe - Nafada',
    'Gombe - Shomgom',
    'Gombe - Yamaltu/Deba',
  ],
  imo: [
    'Imo - Aboh-Mbaise',
    'Imo - Ahiazu-Mbaise',
    'Imo - Ehime-Mbano',
    'Imo - Ezinihitte',
    'Imo - Ideato North',
    'Imo - Ideato South',
    'Imo - Ihitte/Uboma',
    'Imo - Ikeduru',
    'Imo - Isiala Mbano',
    'Imo - Isu',
    'Imo - Mbaitoli',
    'Imo - Ngor-Okpala',
    'Imo - Njaba',
    'Imo - Nkwerre',
    'Imo - Nwangele',
    'Imo - Obowo',
    'Imo - Oguta',
    'Imo - Ohaji/Egbema',
    'Imo - Okigwe',
    'Imo - Orlu',
    'Imo - Orsu',
    'Imo - Oru East',
    'Imo - Oru West',
    'Imo - Owerri North',
    'Imo - Owerri West',
    'Imo - Owerri-Municipal',
    'Imo - Unuimo',
  ],
  jigawa: [
    'Jigawa - Auyo',
    'Jigawa - Babura',
    'Jigawa - Biriniwa',
    'Jigawa - Birnin Kudu',
    'Jigawa - Buji',
    'Jigawa - Dutse',
    'Jigawa - Gagarawa',
    'Jigawa - Garki',
    'Jigawa - Gumel',
    'Jigawa - Guri',
    'Jigawa - Gwaram',
    'Jigawa - Gwiwa',
    'Jigawa - Hadejia',
    'Jigawa - Jahun',
    'Jigawa - Kafin Hausa',
    'Jigawa - Kaugama',
    'Jigawa - Kazaure',
    'Jigawa - Kiri Kasama',
    'Jigawa - Kiyawa',
    'Jigawa - Maigatari',
    'Jigawa - Malam Madori',
    'Jigawa - Miga',
    'Jigawa - Ringim',
    'Jigawa - Roni',
    'Jigawa - Sule Tankarkar',
    'Jigawa - Taura',
    'Jigawa - Yankwashi',
  ],
  kaduna: [
    'Kaduna - Birnin-Gwari',
    'Kaduna - Chikun',
    'Kaduna - Giwa',
    'Kaduna - Igabi',
    'Kaduna - Ikara',
    'Kaduna - Jaba',
    'Kaduna - Jemaa',
    'Kaduna - Kachia',
    'Kaduna - Kaduna North',
    'Kaduna - Kaduna South',
    'Kaduna - Kagarko',
    'Kaduna - Kajuru',
    'Kaduna - Kaura',
    'Kaduna - Kauru',
    'Kaduna - Kubau',
    'Kaduna - Kudan',
    'Kaduna - Lere',
    'Kaduna - Makarfi',
    'Kaduna - Sabon-Gari',
    'Kaduna - Sanga',
    'Kaduna - Soba',
    'Kaduna - Zangon-Kataf',
    'Kaduna - Zarki',
  ],
  kano: [
    'Kano - Ajingi',
    'Kano - Albasu',
    'Kano - Bagwai',
    'Kano - Bebeji',
    'Kano - Bichi',
    'Kano - Bunkure',
    'Kano - Dala',
    'Kano - Dambatta',
    'Kano - Dawakin Kudu',
    'Kano - Dawakin Tofa',
    'Kano - Doguwa',
    'Kano - Fagge',
    'Kano - Gabasawa',
    'Kano - Garko',
    'Kano - Garum Mallam',
    'Kano - Gaya',
    'Kano - Gezawa',
    'Kano - Gwale',
    'Kano - Gwarzo',
    'Kano - Kabo',
    'Kano - Kano Municipal',
    'Kano - Karaye',
    'Kano - Kibiya',
    'Kano - Kiru',
    'Kano - Kumbotso',
    'Kano - Kunchi',
    'Kano - Kura',
    'Kano - Madobi',
    'Kano - Makoda',
    'Kano - Minjibir',
    'Kano - Nassarawa',
    'Kano - Rano',
    'Kano - Rimin Gado',
    'Kano - Rogo',
    'Kano - Shanono',
    'Kano - Sumaila',
    'Kano - Takai',
    'Kano - Tarauni',
    'Kano - Tofa',
    'Kano - Tsanyawa',
    'Kano - Tudun Wada',
    'Kano - Ungogo',
    'Kano - Warawa',
    'Kano - Wudil',
  ],
  katsina: [
    'Katsina - Bakori',
    'Katsina - Batagarawa',
    'Katsina - Batsari',
    'Katsina - Baure',
    'Katsina - Bindawa',
    'Katsina - Charanchi',
    'Katsina - Dan Musa',
    'Katsina - Dandume',
    'Katsina - Danja',
    'Katsina - Daura',
    'Katsina - Dutsi',
    'Katsina - Dutsin-Ma',
    'Katsina - Faskari',
    'Katsina - Funtua',
    'Katsina - Ingawa',
    'Katsina - Jibia',
    'Katsina - Kafur',
    'Katsina - Kaita',
    'Katsina - Kankara',
    'Katsina - Kankia',
    'Katsina - Katsina',
    'Katsina - Kurfi',
    'Katsina - Kusada',
    'Katsina - Mai’adua',
    'Katsina - Malumfashi',
    'Katsina - Mani',
    'Katsina - Mashi',
    'Katsina - Matazu',
    'Katsina - Musawa',
    'Katsina - Rimi',
    'Katsina - Sabuwa',
    'Katsina - Safana',
    'Katsina - Sandamu',
    'Katsina - Zango',
  ],
  kebbi: [
    'Kebbi - Aleiro',
    'Kebbi - Arewa-Dandi',
    'Kebbi - Argungu',
    'Kebbi - Augie',
    'Kebbi - Bagudo',
    'Kebbi - Birnin Kebbi',
    'Kebbi - Bunza',
    'Kebbi - Dandi',
    'Kebbi - Fakai',
    'Kebbi - Gwandu',
    'Kebbi - Jega',
    'Kebbi - Kalgo',
    'Kebbi - Koko/Besse',
    'Kebbi - Maiyama',
    'Kebbi - Ngaski',
    'Kebbi - Sakaba',
    'Kebbi - Shanga',
    'Kebbi - Suru',
    'Kebbi - Wasagu/Danko',
    'Kebbi - Yauri',
    'Kebbi - Zuru',
  ],
  kogi: [
    'Kogi - Adavi',
    'Kogi - Ajaokuta',
    'Kogi - Ankpa',
    'Kogi - Bassa',
    'Kogi - Dekina',
    'Kogi - Ibaji',
    'Kogi - Idah',
    'Kogi - Igalamela-Odolu',
    'Kogi - Ijumu',
    'Kogi - Kabba/Bunu',
    'Kogi - Kogi',
    'Kogi - Lokoja',
    'Kogi - Mopa-Muro',
    'Kogi - Ofu',
    'Kogi - Ogori/Magongo',
    'Kogi - Okehi',
    'Kogi - Okene',
    'Kogi - Olamabolo',
    'Kogi - Omala',
    'Kogi - Yagba East',
    'Kogi - Yagba West',
  ],
  kwara: [
    'Kwara - Asa',
    'Kwara - Baruten',
    'Kwara - Edu',
    'Kwara - Ekiti',
    'Kwara - Ifelodun',
    'Kwara - Ilorin East',
    'Kwara - Ilorin South',
    'Kwara - Ilorin West',
    'Kwara - Irepodun',
    'Kwara - Isin',
    'Kwara - Kaiama',
    'Kwara - Moro',
    'Kwara - Offa',
    'Kwara - Oke-Ero',
    'Kwara - Oyun',
    'Kwara - Pategi',
  ],
  nasarawa: [
    'Nasarawa - Akwanga',
    'Nasarawa - Awe',
    'Nasarawa - Doma',
    'Nasarawa - Karu',
    'Nasarawa - Keana',
    'Nasarawa - Keffi',
    'Nasarawa - Kokona',
    'Nasarawa - Lafia',
    'Nasarawa - Nassarawa',
    'Nasarawa - Nassarawa Egon',
    'Nasarawa - Obi',
    'Nasarawa - Toto',
    'Nasarawa - Wamba',
  ],
  niger: [
    'Niger - Agaie',
    'Niger - Agwara',
    'Niger - Bida',
    'Niger - Borgu',
    'Niger - Bosso',
    'Niger - Chanchaga',
    'Niger - Edati',
    'Niger - Gbako',
    'Niger - Gurara',
    'Niger - Katcha',
    'Niger - Kontagora',
    'Niger - Lapai',
    'Niger - Lavun',
    'Niger - Magama',
    'Niger - Mariga',
    'Niger - Mashegu',
    'Niger - Mokwa',
    'Niger - Muya',
    'Niger - Paikoro',
    'Niger - Rafi',
    'Niger - Rijau',
    'Niger - Shiroro',
    'Niger - Suleja',
    'Niger - Tafa',
    'Niger - Wushishi',
  ],
  ogun: [
    'Ogun - Abeokuta North',
    'Ogun - Abeokuta South',
    'Ogun - Ado-Odo/Ota',
    'Ogun - Egbado North',
    'Ogun - Egbado South',
    'Ogun - Ewekoro',
    'Ogun - Ifo',
    'Ogun - Ijebu East',
    'Ogun - Ijebu North',
    'Ogun - Ijebu North East',
    'Ogun - Ijebu Ode',
    'Ogun - Ikenne',
    'Ogun - Imeko-Afon',
    'Ogun - Ipokia',
    'Ogun - Obafemi-Owode',
    'Ogun - Odeda',
    'Ogun - Odogbolu',
    'Ogun - Ogun Waterside',
    'Ogun - Remo North',
    'Ogun - Shagamu',
  ],
  lagos: [
    'Lagos - Aboru',
    'Lagos - Abraham Adesanya',
    'Lagos - Abule ijesha',
    'Lagos - Abule-egba',
    'Lagos - Agboju',
    'Lagos - Agege',
    'Lagos - Agungi',
    'Lagos - Ajah',
    'Lagos - Ajao estate',
    'Lagos - Akesan',
    'Lagos - Akowonjo',
    'Lagos - Alaba International',
    'Lagos - Amukoko',
    'Lagos - Amuwo odofin',
    'Lagos - Anthony',
    'Lagos - Apapa',
    'Lagos - Awoyaya',
    'Lagos - Ayobo',
    'Lagos - Badagry',
    'Lagos - Badore',
    'Lagos - Bariga',
    'Lagos - Baruwa',
    'Lagos - Bogije',
    'Lagos - Cement',
    'Lagos - Chevron',
    'Lagos - Coker/orile',
    'Lagos - Dopemu',
    'Lagos - Ebute-metta',
    'Lagos - Ebute-metta West/Costain',
    'Lagos - Egbe',
    'Lagos - Egbeda',
    'Lagos - Ejigbo',
    'Lagos - Eko atlantic',
    'Lagos - Epe',
    'Lagos - Fagba',
    'Lagos - Festac town',
    'Lagos - Gbagada',
    'Lagos - Iba',
    'Lagos - Ibeju Lekki',
    'Lagos - Idimu',
    'Lagos - Igando',
    'Lagos - Igbobi',
    'Lagos - Ijegun',
    'Lagos - Ijeshatedo',
    'Lagos - Ijora',
    'Lagos - Iju road',
    'Lagos - Ikate',
    'Lagos - Ikeja',
    'Lagos - Ikeja/Computer Village',
    'Lagos - Ikeja/International Airport',
    'Lagos - Ikorodu',
    'Lagos - Ikota',
    'Lagos - Ikotun',
    'Lagos - Ikoyi',
    'Lagos - Ilasamaja',
    'Lagos - Ilupeju',
    'Lagos - Ipaja',
    'Lagos - Isashi',
    'Lagos - Isheri osun',
    'Lagos - Isolo',
    'Lagos - Itire',
    'Lagos - Iwaya',
    'Lagos - Jakande',
    'Lagos - Jibowu',
    'Lagos - Ketu',
    'Lagos - Kirikiri',
    'Lagos - Lagos Business School',
    'Lagos - Lagos Island',
    'Lagos - Lakowe',
    'Lagos - Lasu',
    'Lagos - Lasu-isheri',
    'Lagos - Lekki Phase 1',
    'Lagos - Magodo Phase 1',
    'Lagos - Magodo Phase 2',
    'Lagos - Makoko',
    'Lagos - Maryland',
    'Lagos - Meiran',
    'Lagos - Mile 12',
    'Lagos - Mile 2',
    'Lagos - Mushin',
    'Lagos - New oko-oba',
    'Lagos - Obadore',
    'Lagos - Obanikoro',
    'Lagos - Obawole',
    'Lagos - Ogba',
    'Lagos - Ogombo',
    'Lagos - Ogudu',
    'Lagos - Ojo',
    'Lagos - Ojodu Berger',
    'Lagos - Ojokoro',
    'Lagos - Ojota',
    'Lagos - Ojuelegba',
    'Lagos - Oke odo',
    'Lagos - Okokomaiko',
    'Lagos - Okota',
    'Lagos - Omole phase 1',
    'Lagos - Omole phase 2',
    'Lagos - Onike',
    'Lagos - Onipanu',
    'Lagos - Oniru',
    'Lagos - Opic Isheri North',
    'Lagos - Oregun',
    'Lagos - Osapa London',
    'Lagos - Oshodi',
    'Lagos - Oworoshoki',
    'Lagos - Palmgrove',
    'Lagos - Pedro',
    'Lagos - Sangotedo',
    'Lagos - Satellite Town',
    'Lagos - Shasha',
    'Lagos - Shomolu',
    'Lagos - Suru-alaba',
    'Lagos - Surulere',
    'Lagos - Trade-Fair',
    'Lagos - VGC',
    'Lagos - Victoria Island',
    'Lagos - Yaba',
  ],
  ondo: [
    'Ondo - Akoko North East',
    'Ondo - Akoko North West',
    'Ondo - Akoko South East',
    'Ondo - Akoko South West',
    'Ondo - Akure North',
    'Ondo - Akure South',
    'Ondo - Ese-Odo',
    'Ondo - Idanre',
    'Ondo - Ifedore',
    'Ondo - Ilaje',
    'Ondo - Ile-Oluji-Okeigbo',
    'Ondo - Irele',
    'Ondo - Odigbo',
    'Ondo - Okitipupa',
    'Ondo - Ondo East',
    'Ondo - Ondo West',
    'Ondo - Ose',
    'Ondo - Owo',
  ],
  osun: [
    'Osun - Aiyedade',
    'Osun - Aiyedire',
    'Osun - Atakunmosa East',
    'Osun - Atakunmosa West',
    'Osun - Boluwaduro',
    'Osun - Boripe',
    'Osun - Ede North',
    'Osun - Ede South',
    'Osun - Egbedore',
    'Osun - Ejigbo',
    'Osun - Ife Central',
    'Osun - Ife East',
    'Osun - Ife North',
    'Osun - Ife South',
    'Osun - Ifedayo',
    'Osun - Ifelod-un',
    'Osun - Ila',
    'Osun - Ilesha East',
    'Osun - Ilesha West',
    'Osun - Irepodu-n',
    'Osun - Irewole',
    'Osun - Isokan',
    'Osun - Iwo',
    'Osun - Obokun',
    'Osun - Odo-Otin',
    'Osun - Ola-Oluwa',
    'Osun - Olorunda',
    'Osun - Oriade',
    'Osun - Orolu',
    'Osun - Osogbo',
  ],
  oyo: [
    'Oyo - Afijio',
    'Oyo - Akinyele',
    'Oyo - Atiba',
    'Oyo - Atisbo',
    'Oyo - Egbedaa',
    'Oyo - Ibadan North',
    'Oyo - Ibadan North East',
    'Oyo - Ibadan North West',
    'Oyo - Ibadan South East',
    'Oyo - Ibadan South West',
    'Oyo - Ibarapa Central',
    'Oyo - Ibarapa East',
    'Oyo - Ibarapa North',
    'Oyo - Ido',
    'Oyo - Irepo',
    'Oyo - Iseyin',
    'Oyo - Itesiwaju',
    'Oyo - Iwajowa',
    'Oyo - Kajola',
    'Oyo - Lagelu',
    'Oyo - Ogbmosho South',
    'Oyo - Ogbomosho North',
    'Oyo - Ogo Oluwa',
    'Oyo - Olorunsogo',
    'Oyo - Oluyole',
    'Oyo - Ona-Ara',
    'Oyo - Orelope',
    'Oyo - Ori Ire',
    'Oyo - Oyo East',
    'Oyo - Oyo West',
    'Oyo - Saki East',
    'Oyo - Saki West',
    'Oyo - Suruleree',
  ],
  plateau: [
    'Plateau - Barkin Ladi',
    'Plateau - Bassaa',
    'Plateau - Bokkos',
    'Plateau - Jos East',
    'Plateau - Jos North',
    'Plateau - Jos South',
    'Plateau - Kanam',
    'Plateau - Kanke',
    'Plateau - Langtang North',
    'Plateau - Langtang South',
    'Plateau - Mangu',
    'Plateau - Mikang',
    'Plateau - Pankshin',
    'Plateau - Qua’an Pan',
    'Plateau - Riyom',
    'Plateau - Shendam',
    'Plateau - Wase',
  ],
  rivers: [
    'Rivers - Abua/Odual',
    'Rivers - Ahoada East',
    'Rivers - Ahoada West',
    'Rivers - Akuku Toru',
    'Rivers - Andoni',
    'Rivers - Asari-Toru',
    'Rivers - Bonny',
    'Rivers - Degema',
    'Rivers - Eleme',
    'Rivers - Emuoha',
    'Rivers - Etche',
    'Rivers - Gokana',
    'Rivers - Ikwerre',
    'Rivers - Khana',
    'Rivers - Obio/Akpor',
    'Rivers - Ogba/Egbema/Ndoni',
    'Rivers - Ogu/Bolo',
    'Rivers - Okrika',
    'Rivers - Omumma',
    'Rivers - Opobo/Nkoro',
    'Rivers - Oyigbo',
    'Rivers - Port-Harcourt',
    'Rivers - Tai',
  ],
  sokoto: [
    'Sokoto - Binji',
    'Sokoto - Bodinga',
    'Sokoto - Dange-Shuni',
    'Sokoto - Gada',
    'Sokoto - Goronyo',
    'Sokoto - Gudu',
    'Sokoto - Gwadabawa',
    'Sokoto - Illela',
    'Sokoto - Isa',
    'Sokoto - Kebbe',
    'Sokoto - Kware',
    'Sokoto - Rabah',
    'Sokoto - Sabon Birni',
    'Sokoto - Shagari',
    'Sokoto - Silame',
    'Sokoto - Sokoto North',
    'Sokoto - Sokoto South',
    'Sokoto - Tambuwal',
    'Sokoto - Tangaza',
    'Sokoto - Tureta',
    'Sokoto - Wamako',
    'Sokoto - Wurno',
    'Sokoto - Yabo',
  ],
  taraba: [
    'Taraba - Ardo-Kola',
    'Taraba - Bali',
    'Taraba - Disputed Areas',
    'Taraba - Donga',
    'Taraba - Gashaka',
    'Taraba - Gassol',
    'Taraba - Ibi',
    'Taraba - Jalingo',
    'Taraba - Karim-Lamido',
    'Taraba - Kurmi',
    'Taraba - Lau',
    'Taraba - Sardauna',
    'Taraba - Takum',
    'Taraba - Ussa',
    'Taraba - Wukari',
    'Taraba - Yorro',
    'Taraba - Zing',
  ],
  yobe: [
    'Yobe - Barde',
    'Yobe - Bursari',
    'Yobe - Damaturu',
    'Yobe - Fika',
    'Yobe - Fune',
    'Yobe - Geidam',
    'Yobe - Gujba',
    'Yobe - Gulani',
    'Yobe - Jakusko',
    'Yobe - Karasuwa',
    'Yobe - Machina',
    'Yobe - Nangere',
    'Yobe - Nguru',
    'Yobe - Potiskum',
    'Yobe - Tarmua',
    'Yobe - Yunusari',
    'Yobe - Yusufari',
  ],
  zamfara: [
    'Zamfara - Anka',
    'Zamfara - Bakura',
    'Zamfara - Birnin Magaji/Kiyaw',
    'Zamfara - Bukkuyum',
    'Zamfara - Bungudu',
    'Zamfara - Gummi',
    'Zamfara - Gusau',
    'Zamfara - Kauran Namoda',
    'Zamfara - Maradun',
    'Zamfara - Maru',
    'Zamfara - Shinkafi',
    'Zamfara - Talata Mafara',
    'Zamfara - Tsafe',
    'Zamfara - Zurmi',
  ],
}

const normalizeLookupValue = (value) => String(value || '').trim().toLowerCase()
const NIGERIAN_STATE_LOOKUP = new Map(
  NIGERIAN_STATES.map((stateName) => [normalizeLookupValue(stateName), stateName]),
)
NIGERIAN_STATE_LOOKUP.set('fct', 'Abuja')
NIGERIAN_STATE_LOOKUP.set('federal capital territory', 'Abuja')
NIGERIAN_STATE_LOOKUP.set('federal capital territory abuja', 'Abuja')

const resolveNigerianStateName = (value) => {
  const normalized = normalizeLookupValue(value).replace(/\s+state$/, '').trim()
  return NIGERIAN_STATE_LOOKUP.get(normalized) || ''
}

const toCityOnlyName = (state, value) => {
  const raw = String(value || '').trim()
  if (!raw) return ''
  const stateName = String(state || '').trim()
  if (stateName) {
    const statePrefix = `${stateName.toLowerCase()} - `
    if (raw.toLowerCase().startsWith(statePrefix)) {
      return raw.slice(statePrefix.length).trim()
    }
  }
  const genericPrefixIndex = raw.indexOf(' - ')
  if (genericPrefixIndex > -1) {
    return raw.slice(genericPrefixIndex + 3).trim()
  }
  return raw
}

const getNigerianCityOptions = (state) => {
  const source = NIGERIAN_CITIES_BY_STATE[normalizeLookupValue(state)] || []
  return Array.from(new Set(source.map((entry) => toCityOnlyName(state, entry)).filter(Boolean)))
}


export {
  DEFAULT_COUNTRY,
  INTERNATIONAL_COUNTRY,
  NIGERIAN_STATES,
  normalizeLookupValue,
  resolveNigerianStateName,
  toCityOnlyName,
  getNigerianCityOptions,
}
