export const FEED_TITLE_POOL = [
  'Selected with love',
  'Handpicked for you',
  'Recommended for you',
  'Curated just for you',
  'Made for your taste',
  'Picked with you in mind',
  'Just for you',
  'Your daily picks',
  'Styled for you',
  'Fresh finds for you',
  'Because you like great style',
  'Chosen with care',
  'Tailored to your taste',
  'Your personal picks',
  'Top picks, just for you',
  'Handpicked favorites',
  'A little something for you',
  'Picks we think you will love',
  'Your next favorite thing',
  'Specially selected for you',
  'Discover something new',
  'Trending picks for you',
]
