create table if not exists public.admin_logistics_rates (
  id bigint generated by default as identity primary key,
  state text not null,
  city text not null,
  price numeric(12,2) not null default 0,
  eta_key text not null default 'next_day',
  eta_hours integer not null default 24,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint admin_logistics_rates_state_city_unique unique (state, city),
  constraint admin_logistics_rates_price_nonnegative check (price >= 0),
  constraint admin_logistics_rates_eta_key_check check (eta_key in ('same_day', 'next_day', 'three_days')),
  constraint admin_logistics_rates_eta_hours_check check (eta_hours >= 1 and eta_hours <= 720)
);

create index if not exists admin_logistics_rates_state_city_idx
  on public.admin_logistics_rates (state, city);

alter table public.admin_logistics_rates enable row level security;

drop policy if exists "Admin logistics rates readable" on public.admin_logistics_rates;
create policy "Admin logistics rates readable"
  on public.admin_logistics_rates
  for select using (true);

drop policy if exists "Admin logistics rates manageable by admins" on public.admin_logistics_rates;
create policy "Admin logistics rates manageable by admins"
  on public.admin_logistics_rates
  for all
  using (public.is_admin_user())
  with check (public.is_admin_user());
