const mockProductListingData = {
  header: {
    eyebrow: 'Products',
    title: 'Products',
    subtitle: 'Track inventory, pricing, and product health in one place.',
    searchPlaceholder: 'Search',
    primaryActionLabel: 'Add Product',
    assistantLabel: 'Assistant',
  },
  overviewCards: [
    {
      id: 'total',
      label: 'Total Products',
      value: '2,483',
      footnote: 'Catalog size',
      series: [12, 18, 15, 20, 18, 24, 22],
      containerClass:
        'rounded-3xl border border-slate-200 bg-gradient-to-br from-slate-100 to-slate-50 p-3 shadow-sm sm:p-4',
      sparkClass: 'text-slate-400',
    },
    {
      id: 'live',
      label: 'Live Products',
      value: '1,932',
      footnote: 'Published products',
      series: [10, 12, 16, 18, 15, 20, 21],
      containerClass:
        'rounded-3xl border border-slate-200 bg-gradient-to-br from-blue-50 to-white p-3 shadow-sm sm:p-4',
      sparkClass: 'text-blue-400',
      hiddenOnMobile: true,
    },
    {
      id: 'revenue',
      label: 'Product Revenue',
      value: '$128,920',
      footnote: 'Total value of listed products',
      series: [80, 84, 78, 92, 88, 94, 99],
      containerClass:
        'rounded-3xl border border-slate-200 bg-gradient-to-br from-emerald-50 to-white p-3 shadow-sm sm:p-4',
      sparkClass: 'text-emerald-500',
      hiddenOnMobile: true,
    },
    {
      id: 'sold',
      label: 'Products Sold',
      value: '18,402',
      delta: { label: '+12%', tone: 'text-emerald-600', suffix: 'vs last 7 days' },
      series: [56, 52, 68, 62, 70, 76, 80],
      containerClass:
        'rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-3 shadow-sm sm:p-4',
      sparkClass: 'text-amber-500',
      hiddenOnMobile: true,
    },
  ],
  statusTabs: [
    { label: 'All Products', value: 'all' },
    { label: 'Active', value: 'publish' },
    { label: 'Draft', value: 'draft' },
    { label: 'Trashed', value: 'trash' },
  ],
  filterOptions: [
    { label: 'All', value: 'all' },
    { label: 'Low Stock', value: 'low_stock' },
    { label: 'Out of Stock', value: 'out_of_stock' },
    { label: 'Featured', value: 'featured' },
  ],
  sortOptions: [
    { label: 'Newest', value: 'newest' },
    { label: 'Best selling', value: 'best_selling' },
    { label: 'Price: High to low', value: 'price_high' },
    { label: 'Price: Low to high', value: 'price_low' },
  ],
  products: [
    {
      id: 9182,
      name: 'OCP Prime Running Sneaker',
      category: 'Footwear',
      status: 'publish',
      statusBadge: { label: 'Active', tone: 'bg-emerald-50 text-emerald-700' },
      stockBadge: { label: 'In stock', tone: 'bg-emerald-50 text-emerald-700' },
      inventoryLabel: '128 units',
      price: 120,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&auto=format&fit=crop',
      isFeatured: true,
    },
    {
      id: 9183,
      name: 'OCP Prime Crossbody Bag',
      category: 'Accessories',
      status: 'publish',
      statusBadge: { label: 'Active', tone: 'bg-emerald-50 text-emerald-700' },
      stockBadge: { label: 'Low stock', tone: 'bg-amber-50 text-amber-700' },
      inventoryLabel: '9 units',
      price: 78,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&auto=format&fit=crop',
      isFeatured: false,
    },
    {
      id: 9184,
      name: 'OCP Prime Utility Jacket',
      category: 'Outerwear',
      status: 'draft',
      statusBadge: { label: 'Draft', tone: 'bg-slate-100 text-slate-600' },
      stockBadge: { label: 'In stock', tone: 'bg-emerald-50 text-emerald-700' },
      inventoryLabel: '54 units',
      price: 148,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&auto=format&fit=crop',
      isFeatured: false,
    },
    {
      id: 9185,
      name: 'OCP Prime Studio Hoodie',
      category: 'Athleisure',
      status: 'publish',
      statusBadge: { label: 'Active', tone: 'bg-emerald-50 text-emerald-700' },
      stockBadge: { label: 'Out of stock', tone: 'bg-rose-50 text-rose-600' },
      inventoryLabel: '0 units',
      price: 96,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&auto=format&fit=crop',
      isFeatured: false,
    },
    {
      id: 9186,
      name: 'OCP Prime Core Tee',
      category: 'Basics',
      status: 'publish',
      statusBadge: { label: 'Active', tone: 'bg-emerald-50 text-emerald-700' },
      stockBadge: { label: 'In stock', tone: 'bg-emerald-50 text-emerald-700' },
      inventoryLabel: '210 units',
      price: 42,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&auto=format&fit=crop',
      isFeatured: false,
    },
  ],
  pagination: {
    shownCount: 5,
    totalCount: 74,
    hasMore: true,
    loadMoreLabel: 'Load more',
  },
  notices: {
    featuredNotice: 'Feature limit reached.',
    emptyStateText: 'No products found.',
    trashNotice: 'Trash items are auto-removed after 30 days.',
  },
  promotedProducts: [
    {
      id: 122,
      name: 'OCP Prime Essentials Set',
      category: 'Bundles',
      price: 190,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&auto=format&fit=crop',
    },
    {
      id: 123,
      name: 'OCP Prime Travel Pack',
      category: 'Accessories',
      price: 86,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&auto=format&fit=crop',
    },
  ],
  recentSoldProducts: [
    {
      id: 201,
      name: 'OCP Prime Performance Leggings',
      category: 'Athleisure',
      quantity: 2,
      total: 136,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&auto=format&fit=crop',
    },
    {
      id: 202,
      name: 'OCP Prime Eco Tote',
      category: 'Accessories',
      quantity: 1,
      total: 32,
      currencySymbol: '$',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&auto=format&fit=crop',
    },
  ],
  reviews: [
    {
      id: 1,
      authorName: 'Jordan K.',
      excerpt: 'Super lightweight and breathable.',
      postTitle: 'OCP Prime Running Sneaker',
      authorAvatarUrl: '',
    },
    {
      id: 2,
      authorName: 'Maya S.',
      excerpt: 'Perfect fit and fast shipping.',
      postTitle: 'OCP Prime Core Tee',
      authorAvatarUrl: '',
    },
  ],
};

export default mockProductListingData;
